language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=alert
  - secure: r0BIKxY4X96o9noVotjxWKuRMbNkcUDrVFJ354xIXF/x8oDCYWe49uqGljPBDHQ7y6Ihsi2H7zIrVaaDvQSaLbn8pI2XuVcb2WSdhhhPjCKUS8OwmdwJjFASdu4/pFpS3ZmrVhDmGFLRSULhPHOYHO5pbNyu30/XbeDyc1352PUITdjfxkd7PsOjG84V3t/Jcev3x+ZUKT9w6HM+YQ2592T++LuCB1EPxkb2HvxA0AYVNl15KwgBEHv2iGTExC+ULHX/LvhTXjin4PQKInNoMIE+PAVHH1sI1V/0lXFdF1i5Li0ht6q837wVMlSfGP1WKtGe/925j36fzjeZtLtaqwg627qMJFlrkc7Q25cCxT3COZL5sHKXZ1RRxr8+H4gGp3syIPy0RqZ7H28XbCCWziEOgsWnLebDUNOY4ZHefsk5OYShdasZOyu0LtdrEpERGYAhygYJRDiGs08AiiTbc8HXH5xGEihXFMW8WXLbBsZGOKkn0fHbd+gq4ZAEXTXWyPqLDl2ux9t8fCf+oU29n+g3s7t9/CoxHjC5dVIfHvzqPopaDrPqGHzg42Prrg9m5Q0Z5Fx2G8ZXnticOLzm4u3TX0JcfKuwzNYWbQakgTLEZwHHUZbJTiVG2qPFhKWkssvSEAzpsrMefezvYCw0bzqjrcDqSwqcT83LgvS+NYQ=
